### ISSUE TITLE
Make `tidynamics` core dependency 

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/transport-analysis#14]
Yes as in you shouldn't be able to use the package without tidynamics tbh. I think we can be opinionated and insist. We didn't for MSD in MDAnalysis core because of the need to keep our dep list as short as possible

_Originally posted by @hmacdope in https://github.com/MDAnalysis/transport-analysis/pull/1#discussion_r1230274126_

**Comment by xhgchen** [comment]
From PR #1:
* Add `tidynamics` to `install_requires=` in `setup.py`
* Remove the "tidynamics was not found" exception
* Remove the skip if no `tidynamics` parts in the tests
* Anything else?

**Comment by hmacdope** [comment]
Thats about it!
