### ISSUE TITLE
Explore allowing all possible permutations for `dim` argument allowed.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/transport-analysis#6]
You could probably make it so that `yx` is ok, I think it would still make logical sense in that the dims don't have an order except by convention, would still follow the `xy` code-path

_Originally posted by @hmacdope in https://github.com/MDAnalysis/transport-analysis/pull/1#discussion_r1212403534_

**Comment by orionarcher** [comment]
Superceded by #13, closing
