### ISSUE TITLE
Write documentation for VACF

### ISSUE THREAD

**Issue by xhgchen** [MDAnalysis/transport-analysis#8]
Once the velocity autocorrelation function (VACF) implementation is merged, it will be time to write the docs. This issue is a reminder to keep the emphasis on being user-friendly and accessible while making links to relevant resources available!

The docs will be written with Read the Docs.

Relevant tutorial: https://docs.readthedocs.io/en/stable/tutorial/

**Comment by xhgchen** [comment]
@orionarcher I see that you have some additional dependencies in your `requirements.yaml` file in SolvationAnalysis like `numpy`, `mdanalysis`, and `pytest`. Are these necessary, and should I be adding dependencies like these to my `requirements.yaml` file too?

**Comment by orionarcher** [comment]
Probably none of those are necessary, tbh I'm not even sure when that file gets read
